### ISSUE TITLE
Combined data

### ISSUE THREAD

**Issue by glwhart** [wsmorgan/kpointTests#1]
Can you make a plot that has both sets of data on one graph? The froyen vs Mueller and the aflow vs Mueller?

Ok if I share the plot with Tim?

**Comment by wsmorgan** [comment]
Yeah I can make the plot. You can share it with whomever you like, that's part of why I put it up here.

**Comment by glwhart** [comment]
I don't see the plot...

**Comment by wsmorgan** [comment]
Sorry. Had a formatting issue with the plot lost night. It's in the plots folder now labeled All_vs_Mueller.pdf.

**Comment by glwhart** [comment]
Great. Can you write a little blurb describing the plot and how the data
was generated? Then I'll send to Tim.

On Tue, May 31, 2016 at 9:21 AM, Wiley Morgan notifications@github.com
wrote:

> Sorry. Had a formatting issue with the plot lost night. It's there now.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wsmorgan/kpointTests/issues/1#issuecomment-222722790,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHdGmM3Q3yjhYvR-n0fNvo8HYp0qI9vHks5qHFHhgaJpZM4IojGz
> .

## 

Gus Hart
http://msg.byu.edu

**Comment by wsmorgan** [comment]
Added a two page pdf that describes how the data was generated and an overview of the plot. It can be found in the plots folder as description.pdf.

**Comment by glwhart** [comment]
For the W and V data, did you still use fcc supercells? Or did you use the actual ground state for the starting point in the enumeration?

**Comment by glwhart** [comment]
Actually, I guess none of them are fcc. Co is hcp, the other two are bcc. In any case, I'm just trying to make sure that they aren't additional things that need to be considered before reporting to Tim.

**Comment by wsmorgan** [comment]
I had them all start with an fcc cell. In all the CONTCARs I looked at after the runs the W and V had relaxed to BCC, I couldn't tell by looking at them if Co had gone HCP but it was definitely still close packed.

**Comment by wsmorgan** [comment]
Now that I have the data for Ti, W, and Al up is there any utility in keeping the Co, and V data?

**Comment by wsmorgan** [comment]
Removed the Co and V data.
